name: WordPress Coding Standards

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  phpcs:
    name: PHP_CodeSniffer
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        tools: composer
        coverage: none
        
    - name: Install PHP_CodeSniffer
      run: |
        composer global require squizlabs/php_codesniffer:"^3.7" --no-interaction --prefer-dist
        
    - name: Allow Composer Plugin
      run: |
        composer global config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
        
    - name: Install WordPress Coding Standards
      run: |
        composer global require wp-coding-standards/wpcs:"^2.3" --no-interaction --prefer-dist
        
    - name: Configure PHPCS
      run: |
        $HOME/.composer/vendor/bin/phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
        
    - name: Run PHPCS
      working-directory: ${{ github.workspace }}
      run: |
        $HOME/.composer/vendor/bin/phpcs --standard=WordPress-Extra --report=summary --extensions=php --ignore=vendor,node_modules,*.min.js,*.min.css,*.zip --runtime-set text_domain coinsub .

